### ISSUE TITLE
[Feat] 메인 페이지 UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPth-MJU-Festival/MJU-Festival-2024-Web#1]
## 🌏 Summary

> 메인 페이지 UI 제작

## ✔️ Task & Description

- [x] 공지사항 버튼 제작
- [x] 네비게이션 바 제작 (스크롤 시 위에 고정)
- [x] 메인 컴포넌트 제작
