### ISSUE TITLE
[Fix] 자잘한 수정

### ISSUE THREAD

**Issue by rlotr02** [DEPth-MJU-Festival/MJU-Festival-2024-Web#16]
## 🌏 Summary

> 자잘한 수정

## ✔️ Task & Description

- [x] 레이아웃 max-width 설정 추가
- [x] 처음에 자동 스크롤 되는 오류 수정
- [x] 이미지 로드 수정
- [x] 버튼 링크 추가
- [x] 같은 탭을 클릭 시 위로 스크롤
- [x] 용량 큰 이미지 webp로 변환
