### ISSUE TITLE
[Feat] 이벤트 Tab UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPth-MJU-Festival/MJU-Festival-2024-Web#19]
## 🌏 Summary

> 이벤트 Tab UI 제작

## ✔️ Task & Description

- [x] 이벤트 Tab UI 제작
- [x] 이벤트 Field UI 제작
- [x] 이벤트 Dropdown UI 제작
