### ISSUE TITLE
[Feat] 제휴 물품 Tab UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPth-MJU-Festival/MJU-Festival-2024-Web#21]
## 🌏 Summary

> 제휴 물품 Tab UI 제작

## ✔️ Task & Description

- [x] 제휴 물품 Tab UI 제작
- [x] 지도 Dropdown UI 제작
- [x] 브랜드 부스 Tab UI 제작
