### ISSUE TITLE
[Feat] 부스 푸드트럭 Tab UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPth-MJU-Festival/MJU-Festival-2024-Web#7]
## 🌏 Summary

> 부스 푸드트럭 Tab UI 제작

## ✔️ Task & Description

- [x] 부스/푸드트럭 Tab 제작
- [x] 부스 컴포넌트 제작
- [x] 푸드트럭 컴포넌트 제작
